// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-analyses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-analyses.ts
var list_analyses_default = defineTool({
  name: "list_analyses",
  title: "List analyses",
  description: "List the signed-in user's analyzed sources (videos, decks, documents), newest first. Optionally filter by topic or title text.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Match against the source title."),
    topic: z.string().trim().min(1).optional().describe("Filter by a topic tag, e.g. 'marketing'."),
    limit: z.number().int().min(1).max(50).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, topic, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("episodes").select(
      "id, title, url, platform, source_type, founders, topics, analysis_status, created_at"
    ).eq("analyzed_by", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (query) request = request.ilike("title", `%${query}%`);
    if (topic) request = request.contains("topics", [topic]);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { analyses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analysis.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_analysis_default = defineTool2({
  name: "get_analysis",
  title: "Get analysis",
  description: "Get one analyzed source the signed-in user can access, with its extracted lessons and personalized insights.",
  inputSchema: {
    analysis_id: z2.string().uuid().describe("Analysis (episode) id from list_analyses.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ analysis_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: episode, error: episodeError } = await supabase.from("episodes").select(
      "id, title, url, platform, source_type, founders, topics, custom_prompt, analysis_status, created_at"
    ).eq("id", analysis_id).maybeSingle();
    if (episodeError) {
      return { content: [{ type: "text", text: episodeError.message }], isError: true };
    }
    if (!episode) {
      return {
        content: [{ type: "text", text: "No analysis found with that id, or access denied." }],
        isError: true
      };
    }
    const { data: lessons, error: lessonsError } = await supabase.from("lessons").select(
      "id, lesson_text, category, founder_attribution, impact_score, actionability_score, personalized_insights(personalized_text, action_items, relevance_score)"
    ).eq("episode_id", analysis_id).order("impact_score", { ascending: false });
    if (lessonsError) {
      return { content: [{ type: "text", text: lessonsError.message }], isError: true };
    }
    const payload = { ...episode, lessons: lessons ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-lessons.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var search_lessons_default = defineTool3({
  name: "search_lessons",
  title: "Search lessons",
  description: "Search the lessons extracted from the signed-in user's analyzed sources by free text, optionally narrowed to a category.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Free text to match inside lesson content."),
    category: z3.string().trim().min(1).optional().describe("Optional lesson category filter."),
    limit: z3.number().int().min(1).max(50).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("lessons").select(
      "id, lesson_text, category, founder_attribution, impact_score, actionability_score, episode_id, episodes!inner(id, title, url, analyzed_by)"
    ).eq("episodes.analyzed_by", ctx.getUserId()).ilike("lesson_text", `%${query}%`).order("impact_score", { ascending: false }).limit(limit ?? 20);
    if (category) request = request.eq("category", category);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-startup-profiles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_startup_profiles_default = defineTool4({
  name: "list_startup_profiles",
  title: "List startup profiles",
  description: "List the signed-in user's startup/company profiles used to personalize insights, so an assistant knows the business context.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_startup_profiles").select("*").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iffcuueutmsusgdfekvm";
var mcp_default = defineMcp({
  name: "founder-mode-advisor",
  title: "Founder Mode Advisor",
  version: "0.1.0",
  instructions: "Tools for Founder Mode Advisor. Use `list_analyses` to browse the user's analyzed videos, decks, and documents, `get_analysis` for one source's extracted lessons and personalized insights, `search_lessons` to find operating lessons by topic, and `list_startup_profiles` for the user's business context. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analyses_default, get_analysis_default, search_lessons_default, list_startup_profiles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
